
export const ICONS = {
    TEXT: `<svg viewBox="0 0 24 24"><path d="M5 4v3h5.5v12h3V7H19V4z"/></svg>`,
    IMAGE: `<svg viewBox="0 0 24 24"><path d="M21 19V5c0-1.1-.9-2-2-2H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V8c0-1.1-.9-2-2-2zm0 12H5V8h14v10zM8.5 13.5l2.5 3.01L14.5 12l4.5 6H5l3.5-4.5z"/></svg>`,
    SQUARE: `<svg viewBox="0 0 24 24"><path d="M3 3h18v18H3z"/></svg>`,
    CIRCLE: `<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="10"/></svg>`,
    DELETE: `<svg viewBox="0 0 24 24"><path d="M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zM19 4h-3.5l-1-1h-5l-1 1H5v2h14V4z"/></svg>`,
    BOLD: `<svg viewBox="0 0 24 24"><path d="M15.6 10.79c.97-.67 1.65-1.77 1.65-2.79 0-2.26-1.75-4-4-4H7v14h7.04c2.09 0 3.71-1.7 3.71-3.79 0-1.52-.86-2.82-2.15-3.42zM10 6.5h3c.83 0 1.5.67 1.5 1.5s-.67 1.5-1.5 1.5h-3v-3zm3.5 9H10v-3h3.5c.83 0 1.5.67 1.5 1.5s-.67 1.5-1.5 1.5z"/></svg>`,
    ITALIC: `<svg viewBox="0 0 24 24"><path d="M10 4v3h2.21l-3.42 8H6v3h8v-3h-2.21l3.42-8H18V4z"/></svg>`,
    UNDERLINE: `<svg viewBox="0 0 24 24"><path d="M12 17c3.31 0 6-2.69 6-6V3h-2.5v8c0 1.93-1.57 3.5-3.5 3.5S8.5 12.93 8.5 11V3H6v8c0 3.31 2.69 6 6 6zm-7 2v2h14v-2H5z"/></svg>`,
    STRIKETHROUGH: `<svg viewBox="0 0 24 24"><path d="M10 19h4v-3h-4v3zM5 4v3h5v3h4V7h5V4H5zM3 14h18v-2H3v2z"/></svg>`,
    ALIGN_LEFT: `<svg viewBox="0 0 24 24"><path d="M15 15H3v2h12v-2zm0-8H3v2h12V7zM3 13h18v-2H3v2zm0 8h18v-2H3v2zM3 3v2h18V3H3z"/></svg>`,
    ALIGN_CENTER: `<svg viewBox="0 0 24 24"><path d="M7 15v2h10v-2H7zm-4 6h18v-2H3v2zm0-8h18v-2H3v2zm4-6v2h10V7H7zM3 3v2h18V3H3z"/></svg>`,
    ALIGN_RIGHT: `<svg viewBox="0 0 24 24"><path d="M3 21h18v-2H3v2zm6-4h12v-2H9v2zm-6-4h18v-2H3v2zm6-4h12V7H9v2zM3 3v2h18V3H3z"/></svg>`,
    ALIGN_JUSTIFY: `<svg viewBox="0 0 24 24"><path d="M3 21h18v-2H3v2zm0-4h18v-2H3v2zm0-4h18v-2H3v2zm0-4h18V7H3v2zm0-6v2h18V3H3z"/></svg>`,
    UPLOAD: `<svg viewBox="0 0 24 24" style="width:18px; height:18px;"><path d="M5 20h14v-2H5v2zm0-10h4v6h6v-6h4l-7-7-7 7z"/></svg>`
};

export const TRANSITIONS = [
    { name: 'slide-fade', label: 'Fade' },
    { name: 'slide-slide-left', label: 'Slide ←' },
    { name: 'slide-slide-right', label: 'Slide →' },
    { name: 'slide-slide-up', label: 'Slide ↑' },
    { name: 'slide-slide-down', label: 'Slide ↓' },
    { name: 'slide-scale-up', label: 'Scale Up' },
    { name: 'slide-scale-down', label: 'Scale Down' },
    { name: 'slide-rotate-cw', label: 'Rotate CW' },
    { name: 'slide-rotate-ccw', label: 'Rotate CCW' },
    { name: 'slide-flip-horizontal', label: 'Flip H' },
    { name: 'slide-flip-vertical', label: 'Flip V' },
    { name: 'slide-cube-left', label: 'Cube ←' },
    { name: 'slide-cube-right', label: 'Cube →' },
    { name: 'slide-wipe-left', label: 'Wipe ←' },
    { name: 'slide-wipe-right', label: 'Wipe →' },
    { name: 'slide-wipe-circle', label: 'Wipe ○' },
    { name: 'slide-blur-in', label: 'Blur' },
    { name: 'slide-pixelate', label: 'Pixelate' },
    { name: 'slide-ken-burns', label: 'Ken Burns' },
    { name: 'slide-morph', label: 'Morph' }
];

export const EASINGS = [
    { val: 'linear', label: 'Linear' },
    { val: 'ease', label: 'Ease' },
    { val: 'ease-in', label: 'Ease In' },
    { val: 'ease-out', label: 'Ease Out' },
    { val: 'ease-in-out', label: 'Ease In-Out' },
    { val: 'cubic-bezier(0.68, -0.55, 0.265, 1.55)', label: 'Bounce' },
    { val: 'cubic-bezier(0.175, 0.885, 0.32, 1.275)', label: 'Elastic' },
    { val: 'cubic-bezier(0.6, -0.28, 0.735, 0.045)', label: 'Back In' },
    { val: 'cubic-bezier(0.175, 0.885, 0.32, 1.275)', label: 'Back Out' }
];

export const CLIP_SHAPES = [
    { val: 'none', label: 'Nenhuma' },
    { val: 'circle', label: 'Círculo' },
    { val: 'ellipse', label: 'Elipse' },
    { val: 'triangle', label: 'Triângulo' },
    { val: 'triangle-inv', label: 'Triângulo Invertido' },
    { val: 'rhombus', label: 'Losango' },
    { val: 'star', label: 'Estrela' },
    { val: 'pentagon', label: 'Pentágono' },
    { val: 'hexagon', label: 'Hexágono' },
    { val: 'octagon', label: 'Octógono' },
    { val: 'heart', label: 'Coração' },
    { val: 'arrow-right', label: 'Seta Direita' },
    { val: 'arrow-left', label: 'Seta Esquerda' },
    { val: 'cross', label: 'Cruz' },
    { val: 'message', label: 'Balão de Fala' },
    { val: 'diamond', label: 'Diamante' },
    { val: 'trapezoid', label: 'Trapézio' },
    { val: 'parallelogram', label: 'Paralelogramo' },
    { val: 'badge', label: 'Badge' },
    { val: 'burst', label: 'Explosão' }
];

export const STATIC_EFFECTS = [
    { val: 'none', label: 'Nenhum' },
    { val: 'stat-shadow-soft', label: 'Sombra Suave' },
    { val: 'stat-shadow-hard', label: 'Sombra Dura' },
    { val: 'stat-shadow-long', label: 'Sombra Longa' },
    { val: 'stat-shadow-inner', label: 'Sombra Interna' },
    { val: 'stat-shadow-neon', label: 'Sombra Neon' },
    { val: 'stat-glow-soft', label: 'Brilho Suave' },
    { val: 'stat-glow-intense', label: 'Brilho Intenso' },
    { val: 'stat-glow-rainbow', label: 'Brilho Arco-íris' },
    { val: 'stat-border-glow', label: 'Borda Brilhante' },
    { val: 'stat-border-dashed', label: 'Borda Tracejada' },
    { val: 'stat-border-dotted', label: 'Borda Pontilhada' },
    { val: 'stat-border-double', label: 'Borda Dupla' },
    { val: 'stat-border-gradient', label: 'Borda Gradiente' },
    { val: 'stat-border-neon', label: 'Borda Neon' },
    { val: 'stat-reflection', label: 'Reflexo' },
    { val: 'stat-3d-emboss', label: '3D Emboss' },
    { val: 'stat-3d-engrave', label: '3D Engrave' },
    { val: 'stat-vintage-sepia', label: 'Sépia' },
    { val: 'stat-vintage-bw', label: 'P&B' },
    { val: 'stat-blur-soft', label: 'Blur Suave' },
    { val: 'stat-blur-motion', label: 'Blur Movimento' },
    { val: 'stat-chrome-metallic', label: 'Metálico' },
    { val: 'stat-glass-morphism', label: 'Vidro Fosco' }
];

export const ANIMATIONS_ENTER = [
    { name: 'none', label: 'Nenhuma' },
    { name: 'fadeIn', label: 'Fade In' },
    { name: 'slideFromBottom', label: 'Slide from Bottom' },
    { name: 'slideFromTop', label: 'Slide from Top' },
    { name: 'slideFromLeft', label: 'Slide from Left' },
    { name: 'slideFromRight', label: 'Slide from Right' },
    { name: 'zoomIn', label: 'Zoom In' },
    { name: 'bounceIn', label: 'Bounce In' },
    { name: 'flipIn', label: 'Flip In' },
    { name: 'rotateIn', label: 'Rotate In' },
    { name: 'swingIn', label: 'Swing In' },
    { name: 'fadeInUp', label: 'Fade In Up' },
    { name: 'fadeInDown', label: 'Fade In Down' },
    { name: 'fadeInLeft', label: 'Fade In Left' },
    { name: 'fadeInRight', label: 'Fade In Right' },
    { name: 'zoomInRotate', label: 'Zoom In Rotate' },
    { name: 'elasticIn', label: 'Elastic In' },
    { name: 'rollIn', label: 'Roll In' },
    { name: 'lightSpeedIn', label: 'Light Speed In' },
    { name: 'jackInTheBox', label: 'Jack In The Box' },
    { name: 'pulseIn', label: 'Pulse In' }
];

export const ANIMATIONS_EXIT = [
    { name: 'none', label: 'Nenhuma' },
    { name: 'fadeOut', label: 'Fade Out' },
    { name: 'slideToBottom', label: 'Slide to Bottom' },
    { name: 'slideToTop', label: 'Slide to Top' },
    { name: 'slideToLeft', label: 'Slide to Left' },
    { name: 'slideToRight', label: 'Slide to Right' },
    { name: 'zoomOut', label: 'Zoom Out' },
    { name: 'bounceOut', label: 'Bounce Out' },
    { name: 'flipOut', label: 'Flip Out' },
    { name: 'rotateOut', label: 'Rotate Out' },
    { name: 'swingOut', label: 'Swing Out' },
    { name: 'fadeOutUp', label: 'Fade Out Up' },
    { name: 'fadeOutDown', label: 'Fade Out Down' },
    { name: 'fadeOutLeft', label: 'Fade Out Left' },
    { name: 'fadeOutRight', label: 'Fade Out Right' },
    { name: 'zoomOutRotate', label: 'Zoom Out Rotate' },
    { name: 'elasticOut', label: 'Elastic Out' },
    { name: 'rollOut', label: 'Roll Out' },
    { name: 'lightSpeedOut', label: 'Light Speed Out' },
    { name: 'jackOutTheBox', label: 'Jack Out The Box' },
    { name: 'pulseOut', label: 'Pulse Out' }
];

export const GEO_OPTIONS = [
    { name: 'none', label: 'Nenhuma' },
    { name: 'geo-rotate-360', label: 'Rotação 360°' },
    { name: 'geo-pulse-scale', label: 'Pulsação Escala' },
    { name: 'geo-shake-h', label: 'Shake Horizontal' },
    { name: 'geo-shake-v', label: 'Shake Vertical' },
    { name: 'geo-skew-alt', label: 'Inclinação Alt.' },
    { name: 'geo-rotate-3d-x', label: 'Rotação 3D X' },
    { name: 'geo-rotate-3d-y', label: 'Rotação 3D Y' },
    { name: 'geo-scale-rotate', label: 'Escala e Rotação' },
    { name: 'geo-pulse-diag', label: 'Pulsação Diagonal' },
    { name: 'geo-rotate-pulse', label: 'Rotação Pulsante' },
    { name: 'geo-elastic-scale', label: 'Escala Elástica' },
    { name: 'geo-rotate-inf-rev', label: 'Rotação Inf. Rev.' },
    { name: 'geo-swing-pendulum', label: 'Pêndulo' },
    { name: 'geo-float-smooth', label: 'Flutuação Suave' },
    { name: 'geo-spiral-grow', label: 'Espiral Crescente' },
    { name: 'geo-twist-dyn', label: 'Torção Dinâmica' },
    { name: 'geo-pulse-3d', label: 'Pulsação 3D' },
    { name: 'geo-rotate-z', label: 'Rotação Z' },
    { name: 'geo-orbit', label: 'Órbita' },
    { name: 'geo-wobble', label: 'Wobble' },
    { name: 'geo-flip-3d', label: 'Flip 3D' },
    { name: 'geo-cube-rotate', label: 'Cubo 3D' },
    { name: 'geo-wave-motion', label: 'Onda' },
    { name: 'geo-bounce-physics', label: 'Física Queda' },
    { name: 'geo-vibrate-intense', label: 'Vibração' },
    { name: 'geo-morph-shape', label: 'Morph Forma' },
    { name: 'geo-elastic-bounce', label: 'Bounce Elástico' },
    { name: 'geo-levitate', label: 'Levitação' },
    { name: 'geo-heartbeat', label: 'Coração' },
    { name: 'geo-jelly-wobble', label: 'Gelatina' },
    { name: 'geo-spiral-in', label: 'Espiral In' },
    { name: 'geo-spiral-out', label: 'Espiral Out' },
    { name: 'geo-spin-accel', label: 'Giro Acelerado' },
    { name: 'geo-tilt-shift', label: 'Tilt Shift' },
    { name: 'geo-figure8', label: 'Figura 8' },
    { name: 'geo-arc-swing', label: 'Arco Swing' },
    { name: 'geo-snap-rotate', label: 'Snap Rotate' },
    { name: 'geo-float-random', label: 'Flutuação Aleatória' },
    { name: 'geo-compress-stretch', label: 'Comprimir/Esticar' },
    { name: 'geo-ripple-center', label: 'Ripple Center' },
    { name: 'geo-tornado-spin', label: 'Tornado' },
    { name: 'geo-pendulum-arc', label: 'Pêndulo Arco' },
    { name: 'geo-step-bounce', label: 'Step Bounce' },
    { name: 'geo-path-follow', label: 'Seguir Caminho' },
    { name: 'geo-swing-chain', label: 'Swing Chain' }
];

export const VIS_OPTIONS = [
    { name: 'none', label: 'Nenhuma' },
    { name: 'vis-shadow-pulse', label: 'Sombra Pulsante' },
    { name: 'vis-neon-pulse', label: 'Neon Pulsante' },
    { name: 'vis-color-cycle', label: 'Ciclo de Cores' },
    { name: 'vis-bright-float', label: 'Brilho Flutuante' },
    { name: 'vis-shadow-move', label: 'Sombra Móvel' },
    { name: 'vis-border-pulse', label: 'Borda Pulsante' },
    { name: 'vis-fog-effect', label: 'Efeito Névoa' },
    { name: 'vis-opacity-tog', label: 'Opacidade Tog.' },
    { name: 'vis-sat-osc', label: 'Saturação Osc.' },
    { name: 'vis-neon-outline', label: 'Contorno Neon' },
    { name: 'vis-glow-int', label: 'Brilho Interno' },
    { name: 'vis-blur-pulse', label: 'Blur Pulsante' },
    { name: 'vis-shadow-col', label: 'Sombra Colorida' },
    { name: 'vis-contrast-pl', label: 'Contraste Pulsante' },
    { name: 'vis-shadow-exp', label: 'Sombra Expansiva' },
    { name: 'vis-neon-dbl', label: 'Neon Duplo' },
    { name: 'vis-bright-pl', label: 'Brilho Pulsante' },
    { name: 'vis-glass-frost', label: 'Vidro Fosco' },
    { name: 'vis-aurora', label: 'Aurora' },
    { name: 'vis-hue-rot', label: 'Rotação de Matiz' },
    { name: 'vis-rainbow-glow', label: 'Arco-íris' },
    { name: 'vis-fire-flicker', label: 'Chama' },
    { name: 'vis-electric-spark', label: 'Elétrico' },
    { name: 'vis-magnetic-pulse', label: 'Magnético' },
    { name: 'vis-crystal-shine', label: 'Cristal' },
    { name: 'vis-hologram-flicker', label: 'Holograma' },
    { name: 'vis-strobe-light', label: 'Strobe' },
    { name: 'vis-pulse-ring', label: 'Anel Pulso' },
    { name: 'vis-energy-aura', label: 'Aura Energia' },
    { name: 'vis-glitch-digital', label: 'Glitch' },
    { name: 'vis-glow-breathe', label: 'Respiração' },
    { name: 'vis-star-twinkle', label: 'Cintilação' },
    { name: 'vis-neon-flicker', label: 'Neon Realista' },
    { name: 'vis-bubble-float', label: 'Bolhas' },
    { name: 'vis-sunray-beams', label: 'Raios Sol' },
    { name: 'vis-liquid-morph', label: 'Morph Líquido' },
    { name: 'vis-prism-shift', label: 'Prisma Shift' },
    { name: 'vis-heat-wave', label: 'Onda Calor' },
    { name: 'vis-plasma-flow', label: 'Plasma Flow' },
    { name: 'vis-radar-sweep', label: 'Radar Sweep' },
    { name: 'vis-scan-line', label: 'Scan Line' },
    { name: 'vis-wave-distort', label: 'Distorção Onda' },
    { name: 'vis-ink-spread', label: 'Tinta Espalhando' },
    { name: 'vis-smoke-rise', label: 'Fumaça' },
    { name: 'vis-matrix-rain', label: 'Matrix Rain' }
];

export const TIMING_OPTIONS = [
    { val: 'linear', label: 'Linear' },
    { val: 'ease', label: 'Ease' },
    { val: 'ease-in', label: 'Ease In' },
    { val: 'ease-out', label: 'Ease Out' },
    { val: 'ease-in-out', label: 'Ease In-Out' },
    { val: 'cubic-bezier(0.68, -0.55, 0.265, 1.55)', label: 'Bounce' },
    { val: 'cubic-bezier(0.175, 0.885, 0.32, 1.275)', label: 'Elastic' },
    { val: 'cubic-bezier(0.6, -0.28, 0.735, 0.045)', label: 'Back In' },
    { val: 'cubic-bezier(0.175, 0.885, 0.32, 1.275)', label: 'Back Out' }
];
